# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  timeout: 5000
  encoding: unicode
  database: spreecommercetest
  pool: 5
  user: postgres
  password: postgres

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: spreecommercetest
  pool: 5
  password:

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: spreecommercedev
  pool: 5
  password:

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: spreecommerceprod
  pool: 5
  password:  